<header class="header menu_2">
		<div id="preloader"><div data-loader="circle-side"></div></div><!-- /Preload -->
		<div id="logo">
			<a href="/"><img src="/assets/img/logo.png" width="149" height="42" alt=""></a>
		</div>
		<ul id="top_menu">
			<li><a href="/login" class="login">Login</a></li>
			<li><a href="#0" class="search-overlay-menu-btn">Search</a></li>
			<li class="hidden_tablet"><a href="/assets/admission.html" class="btn_1 rounded">Admission</a></li>
		</ul>
		<!-- /top_menu -->
		<a href="#menu" class="btn_mobile">
			<div class="hamburger hamburger--spin" id="hamburger">
				<div class="hamburger-box">
					<div class="hamburger-inner"></div>
				</div>
			</div>
		</a>
		<nav id="menu" class="main-menu">
			<ul>
                <li><span><a href="/user/profile">Profile</a></span>
				<li><span><a href="#0">Home</a></span>
					<ul>
						<li><a href="index.html">Home Default</a></li>
						<li><a href="/assets/index-8.html">KenBurns Slider <strong>New!</strong></a></li>
						<li><a href="/assets/index-2.html">Home Video Bg</a></li>
						<li><a href="/assets/index-6.html">Home Flexslider</a></li>
						<li><a href="/assets/index-3.html">Home Layer Slider</a></li>
						<li><a href="/assets/index-4.html">Home FullScreen</a></li>
						<li><a href="/assets/index-7.html">Home Parallax Video</a></li>
						<li><a href="/assets/index-5.html">With Cookie bar (EU law)</a></li>
					</ul>
				</li>
				<li><span><a href="#0">Courses</a></span>
					<ul>
						<li><a href="/courses_list">Courses grid</a></li>
						<li><a href="/courses_list">Courses grid sidebar</a></li>
						<li><a href="/courses_list">Courses list</a></li>
						<li><a href="/courses_list">Courses list sidebar</a></li>
						<li><a href="/courses_list">Course detail</a></li>
                        <li><a href="/assets/course-detail-2.html">Course detail working form</a></li>
						<li><a href="/assets/admission.html">Admission wizard</a></li>
						<li><a href="/assets/teacher-detail.html">Teacher detail</a></li>
					</ul>
				</li>
				<li><span><a href="#0">Pages</a></span>
					<ul>
						<li><a href="/assets/menu_2/index.html">Menu 2</a></li>
						<li><a href="/assets/about.html">About</a></li>
						<li><a href="/assets/blog.html">Blog</a></li>
						<li><a href="/login">Login</a></li>
						<li><a href="/register">Register</a></li>
						<li><a href="/assets/contacts.html">Contacts</a></li>
						<li><a href="/assets/404.html">404 page</a></li>
						<li><a href="/assets/agenda-calendar.html">Agenda Calendar</a></li>
						<li><a href="/assets/faq.html">Faq</a></li>
						<li><a href="/assets/help.html">Help</a></li>
					</ul>
				</li>
				<li><span><a href="#0">Extra Pages</a></span>
					<ul>
						<li><a href="/assets/media-gallery.html">Media gallery</a></li>
						<li><a href="/assets/admin_section/index.html" target="_blank">Admin-Dashboard <strong>New!</strong></a></li>
						<li><a href="/assets/cart-1.html">Cart page 1</a></li>
						<li><a href="/assets/cart-2.html">Cart page 2</a></li>
						<li><a href="/assets/cart-3.html">Cart page 3</a></li>
						<li><a href="/assets/pricing-tables.html">Responsive pricing tables</a></li>
						<li><a href="/assets/coming_soon/index.html">Coming soon</a></li>
						<li><a href="/assets/icon-pack-1.html">Icon pack 1</a></li>
						<li><a href="/assets/icon-pack-2.html">Icon pack 2</a></li>
						<li><a href="/assets/icon-pack-3.html">Icon pack 3</a></li>
						<li><a href="/assets/icon-pack-4.html">Icon pack 4</a></li>
					</ul>
				</li>
				<li><span><a href="https://1.envato.market/Gk0PV" target="_parent">Buy template</a></span></li>
			</ul>
		</nav>
		<!-- Search Menu -->
		<div class="search-overlay-menu">
			<span class="search-overlay-close"><span class="closebt"><i class="ti-close"></i></span></span>
			<form role="search" id="searchform" method="get">
				<input value="" name="q" type="search" placeholder="Search..." />
				<button type="submit"><i class="icon_search"></i>
				</button>
			</form>
		</div><!-- End Search Menu -->
	</header>